- name: Copy Openbox configuration files
  copy: src=openbox/ dest=/home/vagrant/.config/openbox owner={{ def_user }} group={{ def_user }}

- name: Copy Openbox theme files
  copy: src=openbox/FlatSolid/ dest=/usr/share/themes/FlatSolid owner={{ def_user }} group={{ def_user }}

- name: Copy Terminator configuration files
  copy: src=terminator/ dest=/home/vagrant/.config/terminator owner={{ def_user }} group={{ def_user }}

- name: Copy Tint2 configuration files
  copy: src=tint2/grey_tint2rc dest=/home/vagrant/.config/tint2/ owner={{ def_user }} group={{ def_user }}

- name: Copy Conky configuration files
  copy: src=conky/.conkyrc dest=/home/vagrant/.config/ owner={{ def_user }} group={{ def_user }}

- name: Copy Compton configuration files
  copy: src=compton.conf dest=/home/vagrant/.config/ owner={{ def_user }} group={{ def_user }}

- name: Copy GTK3 configuration files
  copy: src=gtk/settings.ini dest=/home/vagrant/.config/gtk-3.0/ owner={{ def_user }} group={{ def_user }}

- name: Copy background image
  copy: src=bg/grey.png dest=/home/vagrant/ owner={{ def_user }} group={{ def_user }}

#- name: Enable Xfce
#  shell: systemctl isolate graphical.target

#- name: Set Xfce Default
#  shell: systemctl set-default graphical.target

- name: Add custon PS1 to .bashrc
  lineinfile: dest=/home/{{ def_user }}/.bashrc line=PS1='\[\033[38;5;208m\]\u\[\033[0m\]@\h [\[$(tput sgr0)\]\[\033[38;5;208m\]\w\\[\033[0m\]]\n\[$(tput bold)\]\[\033[0m\]>>\[$(tput sgr0)\]  ' state=present

#- name: Replace lightdm
#  copy: src=lightdm/lightdm-gtk-greeter.conf dest=/etc/lightdm/lightdm-gtk-greeter.conf

#- name: Replace lightdm
#  copy: src=lightdm/lightdm.conf dest=/etc/lightdm/lightdm.conf
#- name: Restart system
#  shell: init 6
#conky -c ~/.config/.conkyrc
#tint2 -c ~/.config/grey_tint2rc
#compton