---
- name: Install Xorg Desktop
  package:
    name: "{{item}}"
    state: present
  with_items:
    - xorg-server
    - xorg-apps
    - xorg-xinit
    - xorg-twm
    - xterm
#    - xcompmgr
#    - transset-df

- name: Install LightDM Desktop
  package:
    name: "{{item}}"
    state: present
  with_items:
    - lightdm
    - lightdm-gtk-greeter

- name: Enable LightDM
  systemd:
    name: lightdm.service
    enabled: yes

- name: Install Xfce4 Desktop
  package:
    name: "{{item}}"
    state: present
  with_items:
    - xfce4
    - xfce4-goodies

- name: Install Openbox & Utils
  package:
    name: "{{item}}"
    state: present
  with_items:
    - obmenu
    - openbox
    - obconf
    - compton
    - tint2
    - conky
#    - nitrogen
    - feh
    - slock
    - lxappearance
    - ttf-liberation
    - ttf-roboto
    - arc-gtk-theme
    - arc-icon-theme

#    - arc-icon-theme
#    - arc-icon-theme-git
