---
- name: Add docker group
  group:
    name: docker
    state: present

#- name: Make sure we have a 'wheel' group
#  group:
#    name: wheel
#    state: present
#
#- name: Allow 'wheel' group to have passwordless sudo
#  lineinfile:
#    dest: /etc/sudoers
#    state: present
#    regexp: '^%wheel'
#    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#    validate: 'visudo -cf %s'

- name: Add default sudo user
  user:
    name: "{{ default_sudo_user }}"
    groups: docker
    append: yes
    state: present