- name: Run the equivalent of "pacman -Syu"
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_to_install }}"

- name: Install boto3 (AWS support)
  pip:
    name: boto3
#    version: 1.7.13

- name: Install awscli (AWS support)
  pip:
    name: awscli
#    version: 1.15.13
#    extra_args: --upgrade